version: '3'

services:

  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html

  db:
    image: postgres:14.5
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-test_db}
      POSTGRES_USER: ${DB_USERNAME:-test_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-test_pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  webserver:
    image: nginx:latest
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app

volumes:
  postgres-data:
