version: '3'

services:

  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
    networks:
      - local-net

  database:
    container_name: database
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-test_db}
      POSTGRES_USER: ${DB_USERNAME:-test_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-test_pass}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local-net

  webserver:
    image: nginx:latest
    container_name: nginx-webserver
    restart: unless-stopped
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/nginx.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - local-net

  adminer:
    image: adminer
    restart: always
    ports:
      - "9001:8080"
    networks:
      - local-net

volumes:
  postgres-data:

networks:
  local-net:
    driver: bridge